[build-system]
requires = ["setuptools", "wheel", "setuptools_scm[toml]==7.* "]
build-backend = "setuptools.build_meta"

[project]
name = "retrofy"
dynamic = [
  "version",  # The version is taken directly from the repository, using setuptools-scm.
]
description = "A tool to convert modern Python code to less modern Python versions"
readme = "README.md"
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
]
authors = [
  { name = "Phil Elson", email = "pelson.pub@gmail.com" },
]
requires-python = ">=3.9"
license = "Apache-2.0"

# The core dependencies of the project.
dependencies = [
  "libcst",
  "setuptools-ext",  # TODO: Get rid of this dependency when there is a wheel interface elsewhere.
]

[project.optional-dependencies]
test = [
  "pytest",
]
doc = [
]
dev = [
  "retrofy[doc,test]",
]

[project.urls]
Homepage = "https://gitlab.cern.ch/pelson/retrofy"

[tool.setuptools.packages.find]
include = ["retrofy", "retrofy.*"]

[tool.setuptools_scm]
write_to = "retrofy/_version.py"

[project.entry-points.multistage_build]
# Declare automatic hooks for a multistage-build using project.
post-build-wheel = "retrofy._pep517_hooks:compatibility_via_rewrite"
post-build-editable = "retrofy._pep517_hooks:compatibility_via_import_hook"
