name: Publish to PyPI

on:
  workflow_run:
    workflows: ["python-test"]   # Must match the test workflow name exactly
    types:
      - completed

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    # Only run if tests passed AND it's a release tag
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      startsWith(github.event.workflow_run.head_branch, 'refs/tags/')

    permissions:
      id-token: write   # Required for PyPI Trusted Publishing
      contents: read

    environment:
      name: pypi
      url: https://pypi.org/p/retrofy

    steps:
      - name: Download tested distributions
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
